//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luach.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Luach.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;LS&gt;&lt;L N=&quot;Melbourne&quot;&gt;&lt;T&gt;10&lt;/T&gt;&lt;E&gt;35&lt;/E&gt;&lt;LT&gt;-37.82&lt;/LT&gt;&lt;LN&gt;-144.97&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Aukland&quot;&gt;&lt;T&gt;12&lt;/T&gt;&lt;E&gt;0&lt;/E&gt;&lt;LT&gt;-36.87&lt;/LT&gt;&lt;LN&gt;-174.77&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Boisbriand&quot;&gt;&lt;T&gt;-5&lt;/T&gt;&lt;E&gt;0&lt;/E&gt;&lt;LT&gt;45.62&lt;/LT&gt;&lt;LN&gt;73.85&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ottawa&quot;&gt;&lt;T&gt;-5&lt;/T&gt;&lt;E&gt;0&lt;/E&gt;&lt;LT&gt;45.42&lt;/LT&gt;&lt;LN&gt;75.7&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Winnipeg&quot;&gt;&lt;T&gt;-6&lt;/T&gt;&lt;E&gt;0&lt;/E&gt;&lt;LT&gt;49.88&lt;/LT&gt;&lt;LN&gt;97.13&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Toronto&quot;&gt;&lt;T&gt;-5&lt;/T&gt;&lt;E&gt;175&lt;/E&gt;&lt;LT&gt;43.68&lt;/LT&gt;&lt;LN&gt;79.43&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Montreal&quot;&gt;&lt;T&gt;-5&lt;/T&gt;&lt;E&gt;30&lt;/E&gt;&lt;LT&gt;45.52&lt;/LT&gt;&lt;LN&gt;73.57&lt;/LN&gt;&lt;....
        /// </summary>
        internal static string LocationsList {
            get {
                return ResourceManager.GetString("LocationsList", resourceCulture);
            }
        }
    }
}
