//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZmanimAnywhere.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZmanimAnywhere.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Earth {
            get {
                object obj = ResourceManager.GetObject("Earth", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;LS&gt;&lt;L N=&quot;Ofakim&quot; H=&quot;אופקים&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;E&gt;170&lt;/E&gt;&lt;LT&gt;31.32&lt;/LT&gt;&lt;LN&gt;-34.62&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Eilat&quot; H=&quot;אילת&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;29.55&lt;/LT&gt;&lt;LN&gt;-34.95&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Elad&quot; H=&quot;אלעד&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;E&gt;150&lt;/E&gt;&lt;LT&gt;32.05&lt;/LT&gt;&lt;LN&gt;-34.95&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ashdod&quot; H=&quot;אשדוד&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.78&lt;/LT&gt;&lt;LN&gt;-34.63&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ashkelon&quot; H=&quot;אשקלון&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.65&lt;/LT&gt;&lt;LN&gt;-34.57&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Be&apos;er Ya&apos;akov&quot; H=&quot;באר יעקב&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.93&lt;/LT&gt;&lt;LN&gt;-34.83&lt;/LN&gt;....
        /// </summary>
        internal static string LocationsList {
            get {
                return ResourceManager.GetString("LocationsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;LS&gt;&lt;L N=&quot;Ofakim&quot; H=&quot;אופקים&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;E&gt;170&lt;/E&gt;&lt;LT&gt;31.32&lt;/LT&gt;&lt;LN&gt;-34.62&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Eilat&quot; H=&quot;אילת&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;29.55&lt;/LT&gt;&lt;LN&gt;-34.95&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Elad&quot; H=&quot;אלעד&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;E&gt;150&lt;/E&gt;&lt;LT&gt;32.05&lt;/LT&gt;&lt;LN&gt;-34.95&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ashdod&quot; H=&quot;אשדוד&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.78&lt;/LT&gt;&lt;LN&gt;-34.63&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Ashkelon&quot; H=&quot;אשקלון&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.65&lt;/LT&gt;&lt;LN&gt;-34.57&lt;/LN&gt;&lt;/L&gt;&lt;L N=&quot;Be&apos;er Ya&apos;akov&quot; H=&quot;באר יעקב&quot; I=&quot;Y&quot;&gt;&lt;T&gt;2&lt;/T&gt;&lt;LT&gt;31.93&lt;/LT&gt;&lt;LN&gt;-34.83&lt;/LN&gt;....
        /// </summary>
        internal static string LocationsList1 {
            get {
                return ResourceManager.GetString("LocationsList1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html; charset=utf-8&quot; /&gt;
        ///    &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=Edge&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    #--DIRECTION--#
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
    }
}
